management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  metrics:
    distribution:
      percentiles[http.server.requests]: 0.9, 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      slo[http.server.requests]: 10ms, 100ms
